apiVersion: v1
kind: Service
metadata:
  name: smoke-test
  namespace:  {{.Release.Name}}
  labels:
    app.kubernetes.io/name: "smoke-test"
spec:
  selector:
    app.kubernetes.io/name: "smoke-test"
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
