{{if .Values.httpRoute.enabled}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{.Values.httpRoute.parent.name}}
      namespace: {{.Values.httpRoute.parent.namespace}}
      sectionName: {{.Values.httpRoute.parent.sectionName}}
  hostnames:
    - {{.Values.httpRoute.host}}
  rules:
    - backendRefs:
        - name: {{.Release.Name}}-{{.Chart.Name}}
          port: {{.Values.service.port}}
      matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /admin
    - matches:
        - path:
            type: PathPrefix
            value: /
          method: GET
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /admin/
---
{{end}}
