{{if .Values.ipPools.enabled}}
{{- range .Values.ipPools.pools }}
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{.name}}
  namespace: {{$.Release.Namespace}}
spec:
  blocks:
    - start: {{.start}}
      stop: {{.stop}}
{{end}}
{{end}}
