tf: 2

httpRoute:
  enabled: true
  host: "hubble.kind.local"
  parent:
    name: private-http
    namespace: gateways
    sectionName: http
  backend:
    name: hubble-ui
    port: 80
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "hubble.kind.local"
